[tool.black]
line-length = 100
target-version = ['py39']
skip-string-normalization = false

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 100

[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]
max-complexity = 10
